version: 2
 
jobs:
 test:
   docker:
     - image: cypress/base:10.15.3
   steps:
     - checkout
     # restore folders with npm dependencies and Cypress binary
     - restore_cache:
         name: Restore Yarn Package Cache
         keys:
           - yarn-packages-{{ checksum "yarn.lock" }}
     # install npm dependencies and Cypress binary
     # if they were cached, this step is super quick
     - run:
         name: Install dependencies
         command: YARN_PRODUCTION=false yarn install --frozen-lockfile
     - run: npm run cy:verify
     # save npm dependencies and Cypress binary for future runs
     - save_cache:
         name: Save Yarn Package Cache
         key: yarn-packages-{{ checksum "yarn.lock" }}
         paths:
           - ~/.cache/yarn
     # start server before starting tests
     - run:
         command: yarn start
         background: true
     - run: yarn run e2e:record --key ${CYPRESS_REC_KEY}
 
workflows:
 version: 2
 deployment:
   jobs:
     - test
